### ISSUE TITLE
Auto-naming does not work for datadog resources

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-datadog#508]
### What happened?

Looks like we don't auto-name some (all?) resources in datadog:
https://github.com/pulumi/pulumi-datadog/pull/506

All the resource with RandomString names are ones which failed without a name parameter. We handle this for other providers, seems reasonable to do the same for datadog.

### Example

```yaml
name: index_apikeyGrx1Jo4mtRy8
runtime: yaml
description: ""
config:
  pulumi:tags:
    value:
      pulumi:template: https://www.pulumi.com/ai/api/project/cef5cfba-6f6d-4ef1-afac-fe029857cdf5.zip
resources:
  datadogApiKey:
    type: datadog:ApiKey
```

fails, but succeeds with a name property. Same for:

```yaml
name: index_logscustompipelineqAzO442RDaIa
runtime: yaml
description: ""
config:
  pulumi:tags:
    value:
      pulumi:template: https://www.pulumi.com/ai/api/project/ffddeb16-4a62-4703-be3a-e13744251a78.zip
resources:
  logs-custom-pipeline:
    properties:
      filters:
        - query: source:python
      isEnabled: true
      processors: []
    type: datadog:LogsCustomPipeline
```

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
